=== RachelBdeS/RachelBdeS.github.io/_Sommaire/Cours/ressources/chapitre22.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- L'historique de cette DTD présentant ses diverses versions est dans le fichier historiqueChapitre.dtd.txt-->

<!-- ================ Declarations d'entites ============================= -->
<!--<!ENTITY % HTMLspecial PUBLIC "-//W3C//ENTITIES Special for XHTML//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml-special.ent">-->
<!ENTITY % HTMLspecial SYSTEM "xhtml-special.ent">
%HTMLspecial;
<!ENTITY % URI "CDATA">
<!ENTITY % enligne "#PCDATA | definition | valeur | index | autrelangue | code | reference | acronyme | abreviation| image | logiciel | puissance">
<!ENTITY % bloc "image | texte | liste | définitions | exemple | exemplejavascript | exemple_css | tableau | imagereactive">
<!-- =================== Declarations d'elements ============================== -->
<!ELEMENT chapitre (cours, entete, corpus)>
	<!ATTLIST chapitre  typecourssiteweb (xml|html|dhtml) #REQUIRED>
<!ELEMENT cours (#PCDATA)>
<!-- Nom du fichier XML sans l'extension -->
	<!ATTLIST cours nomfichier CDATA #REQUIRED >
<!--    Declarations des elements de l'entete     -->
	<!ELEMENT entete (titre, auteur, resume, motsclefs)>
		<!ELEMENT titre (#PCDATA)>
		<!ELEMENT auteur (#PCDATA)>
			<!ATTLIST auteur
				email CDATA #IMPLIED
			>
			
	<!ELEMENT resume (#PCDATA)>
	<!ELEMENT motsclefs (#PCDATA)>
	
<!--  Declarations des elements du corps du cours   -->
<!ELEMENT corpus (partie*, bibliographie?)>
<!ELEMENT partie (section | exercice | paragraphe)*>
<!ELEMENT section (paragraphe | liste | exercice)*>
<!ELEMENT paragraphe (%bloc;)*>
<!ATTLIST paragraphe
	titre CDATA #IMPLIED
	auteur CDATA ""
	date CDATA ""
	href %URI; ""
	ancre ID #IMPLIED
>
<!ELEMENT liste (item)*>

<!ELEMENT item (%bloc;)*>
<!ATTLIST liste
	type (envrac | ordonnee | sanspuce) "envrac"
>

<!ELEMENT définitions (terme,def+)+>

<!ELEMENT terme (%enligne;)* >
<!ELEMENT def (%enligne;)* >

<!ELEMENT tableau (groupecolonne*,ligne*, legende?)>
<!ATTLIST tableau
	bordure CDATA "1"
>
<!ELEMENT groupecolonne EMPTY>
	<!ATTLIST groupecolonne
		nombre CDATA "1"
		largeur CDATA #IMPLIED
	>
<!ELEMENT ligne (colonne*)>
<!ELEMENT colonne (%bloc;)*>
<!ATTLIST colonne
	type (header | normal) "normal"
	id ID #IMPLIED
	abbr CDATA #IMPLIED
	headers IDREFS #IMPLIED
>
<!ATTLIST ligne
	type (header | normal) "normal"
>
<!ELEMENT legende (%enligne;)*>

<!ELEMENT image (legende?)>
<!ATTLIST image
	src %URI; #REQUIRED
	hauteur CDATA ""
	largeur CDATA ""
	alt CDATA #REQUIRED
	classe (normal | illustration) "normal"
>
<!ELEMENT imagereactive (zone+, legende?)>
<!ATTLIST imagereactive
	src %URI; #REQUIRED
	hauteur CDATA ""
	largeur CDATA ""
	alt CDATA #REQUIRED
	nom CDATA #REQUIRED
>
<!ELEMENT zone EMPTY>
<!ATTLIST zone
	forme (rect | circle | poly | default) "rect"
	coords CDATA #IMPLIED
	href %URI; #IMPLIED
	alt CDATA #REQUIRED
>
<!ELEMENT texte (%enligne;)*>
<!ATTLIST section
	titre CDATA #REQUIRED
	auteur CDATA ""
	date CDATA ""
	href %URI; ""
	ancre ID #REQUIRED
>
<!ELEMENT exercice (remarque?,enonce?, correction*)>
<!ELEMENT remarque (#PCDATA)>
<!ELEMENT enonce EMPTY>
<!ATTLIST enonce
	href %URI; ""
>
<!ELEMENT correction EMPTY>
<!ATTLIST correction
	href %URI; #REQUIRED
	description CDATA #IMPLIED
>
<!ATTLIST exercice
	titre CDATA #REQUIRED
	auteur CDATA ""
	date CDATA ""
	ancre ID #REQUIRED
>
<!ATTLIST partie
	titre CDATA #REQUIRED
	auteur CDATA ""
	date CDATA ""
	href %URI; ""
	ancre ID #REQUIRED
>

<!-- Definitions d'elements en-ligne -->
<!ELEMENT acronyme (#PCDATA)>
	<!ATTLIST acronyme
		titre CDATA #REQUIRED
		lang CDATA #IMPLIED
	>
<!ELEMENT abreviation (#PCDATA|code)*>
	<!ATTLIST abreviation
		titre CDATA #REQUIRED
		lang CDATA #IMPLIED
	>
<!ELEMENT index (#PCDATA)>
<!ATTLIST index
	type (visible | hidden) "hidden"
	id ID #REQUIRED
>
<!ELEMENT definition (#PCDATA)>
<!ATTLIST definition
	clef CDATA #REQUIRED
	lang CDATA #IMPLIED
>

<!ELEMENT autrelangue (%enligne;)*>
<!ATTLIST autrelangue
	type CDATA "en"
>
<!ELEMENT valeur ANY>
<!ATTLIST valeur
 	lang CDATA #IMPLIED
 >
<!ELEMENT code (#PCDATA)>
<!ATTLIST code
	type (langage | code | typefichier) "code"
	option (yes | no) "no"
>
<!ELEMENT logiciel (#PCDATA)* >
<!ATTLIST logiciel
 	lang CDATA #IMPLIED
 >

<!ELEMENT exemple (prologue | instruction_traitement | element | commentaire | typedocument | cdat | declaration_element | declaration_entite | typedocument_interne)*>
<!ATTLIST exemple
	type (XML | HTML | illustration) #REQUIRED
	ancre ID #IMPLIED
>

<!ELEMENT prologue EMPTY>
<!ATTLIST prologue
	encodage CDATA "ISO-8859-1"
	version CDATA "1.0"
	standalone (yes | no) #IMPLIED 
>

<!ELEMENT instruction_traitement EMPTY >
<!ATTLIST instruction_traitement
	nom CDATA #REQUIRED
	type CDATA #REQUIRED
	href %URI; #REQUIRED
>

<!ELEMENT element (#PCDATA | attribut |commentaire | element | cdat | contenu)* >
<!ATTLIST element
 	nom CDATA #REQUIRED
 	enligne (oui | non) "non"
 	indent (oui | non) "non"
	niveau CDATA "0"
	vide (oui | non) "non"
 >
 
 <!ELEMENT contenu (#PCDATA)>
 <!-- Cet élément est réservé aux éléments non en ligne pour lequel un contenu doit être inséré à la ligne. Par exemple :<style>
     (...)
 </style>
 -->
 <!ATTLIST contenu niveau CDATA "0" >
 
 <!ELEMENT attribut (#PCDATA)>
 <!ATTLIST attribut
 	nom CDATA #REQUIRED
 	pseudo (non | oui) "non"
 >
 
 <!ELEMENT commentaire (#PCDATA)>
 	<!ATTLIST commentaire niveau CDATA "0">
  <!ELEMENT cdat (#PCDATA)>
  
  <!ELEMENT typedocument EMPTY>
  <!ATTLIST typedocument
  	nomracine CDATA #REQUIRED
  	type (SYSTEM|PUBLIC|...) #REQUIRED
  	identifiant CDATA #IMPLIED
  	href %URI; #REQUIRED
 >
 
 <!ELEMENT typedocument_interne (declaration_element | declaration_entite)*>
   <!ATTLIST typedocument_interne
  	nomracine CDATA #REQUIRED
  >
 
 <!ELEMENT declaration_element (declaration_attribut*)>
 <!ATTLIST declaration_element
 	nom CDATA #REQUIRED
 	type CDATA #REQUIRED
 >
 
  <!ELEMENT declaration_attribut EMPTY>
 <!ATTLIST declaration_attribut
 	nomattr CDATA #REQUIRED
 	valeur CDATA #REQUIRED
 	type (IMPLIED | REQUIRED | FIXED | chaine) #REQUIRED
 	defaut CDATA #IMPLIED
 >
 
 <!ELEMENT declaration_entite EMPTY>
  <!ATTLIST declaration_entite
 	nom CDATA #REQUIRED
 	valeur CDATA #REQUIRED
 	type (paramétrique | caractères) "caractères"
 	syspub (system | public | autre) "autre"
 	identifiant CDATA #IMPLIED
 >

<!ELEMENT exemple_css (csselt|commentaireCSS)* >
<!ELEMENT commentaireCSS (#PCDATA) >
<!ELEMENT csselt (selecteur, prop+)>
<!ELEMENT selecteur (#PCDATA)>
<!ELEMENT prop EMPTY>
<!ATTLIST prop
	nom CDATA #REQUIRED
	valeur CDATA #REQUIRED
>
	
<!ELEMENT exemplejavascript (fonction | instruction | variable | propriete | declaration | autres | finligne | sautligne | bloc | commentaire_js)*>
<!ELEMENT bloc (fonction | instruction | variable | propriete | declaration | autres | finligne | sautligne | bloc | commentaire_js)* >
	<!ATTLIST bloc
		niveau CDATA "0"
		avec_retour (vrai|faux) "vrai">
<!ELEMENT fonction (variable | autres | propriete | fonction)*>
	<!ATTLIST fonction
		name CDATA #REQUIRED
		niveau CDATA "0">
<!ELEMENT instruction EMPTY>
	<!ATTLIST instruction
		name CDATA #REQUIRED
		niveau CDATA "0">
<!ELEMENT variable EMPTY>
	<!ATTLIST variable
		name CDATA #REQUIRED
		niveau CDATA "0">
<!ELEMENT propriete EMPTY>
	<!ATTLIST propriete
		name CDATA #REQUIRED
		niveau CDATA "0">
<!ELEMENT declaration EMPTY>
	<!ATTLIST declaration
		nomvariable CDATA #REQUIRED
		valeur CDATA #REQUIRED
		new (oui|non) "oui"
		niveau CDATA "0">
<!ELEMENT autres (#PCDATA)>
	<!ATTLIST autres niveau CDATA "0" >
<!ELEMENT finligne EMPTY>
	<!ATTLIST finligne caractère CDATA ";" >
<!ELEMENT sautligne EMPTY>
<!ELEMENT commentaire_js (#PCDATA|sautligne)*>
	<!ATTLIST commentaire_js niveau CDATA "0" >

<!ELEMENT reference ANY>
<!ATTLIST reference
	href %URI; #REQUIRED
	lang CDATA #IMPLIED
>

<!ELEMENT puissance (#PCDATA) >

<!ELEMENT bibliographie (author, titre, editeur, lien, commentaire)?>
<!ELEMENT author (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT editeur (#PCDATA)>
<!ELEMENT lien (#PCDATA)>
<!ATTLIST bibliographie
	auteur CDATA ""
	date CDATA ""
	href %URI; ""
>

=== RachelBdeS/RachelBdeS.github.io/_Sommaire/Cours/html/listes.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE chapitre SYSTEM "../ressources/chapitre22.dtd">

<chapitre typecourssiteweb="html">
	<cours nomfichier="listes">Cours de HTML</cours>
	<entete>
		<titre>Les listes</titre>
		<auteur email="Gilles.Chagnon@upmc.fr">G. Chagnon</auteur>
		<resume>Ce chapitre présente la gestion des listes en HTML.</resume>
		<motsclefs>html, base, liste, ul, ol, li, dl, dd, dt, list</motsclefs>
	</entete>
	<corpus>
		<partie ancre="listes" titre="Listes">
			<section ancre="listesintro" titre="Introduction">
				<paragraphe>
					<texte>Très tôt, en raison de l'historique du <code type="langage">HTML</code>, la notion de liste est apparue, car elle permet de structurer simplement un ensemble de données. Cinq types de listes différents existent&#160;: les listes non ordonnées, les listes numérotées, les listes de définition d'une part, qui sont encore utilisées, et les listes de type répertoire et de menu d'autre part, qui sont maintenant tombées en désuétude. Ce cours se limite aux premiers types de listes.</texte>
				</paragraphe>
			</section>
			<section ancre="listestypes" titre="Les types de listes">
				<paragraphe ancre="li" titre="la balise &lt;li&gt;">
					<texte>Cette balise sert à délimiter un élément de liste, et est toujours incluse dans un environnement de liste. Elle ne possède qu'un unique attribut, valable uniquement en <code type="langage">HTML</code> transitionnel, <code>type</code>.</texte>
					<texte><code>type</code> peut prendre les valeurs <code>disc</code> (valeur par défaut pour un premier niveau d'<reference href="#imbriquees">imbrication</reference> d'une <reference href="#puces">liste à puces</reference>), <code>circle</code> ou <code>square</code>.</texte>
				</paragraphe>
				<paragraphe ancre="puces" titre="Listes à puces">
					<texte>C'est le type de liste le plus simple. Elle s'introduit en utilisant la balise <code><![CDATA[<ul>]]></code>, qui signifie <autrelangue> <valeur>U</valeur>nordered <valeur>L</valeur>ist</autrelangue>. Elle possède le même attribut que la balise <code>&lt;li&gt;</code>, qui s'utilise dans les mêmes conditions, et est également <valeur>obsolète en HTML&#160;4.01 strict</valeur>&#160;:</texte>
					<tableau>
						<ligne type="header">
							<colonne id="attr_ul"><texte>Attribut</texte></colonne>
							<colonne id="effet_ul"><texte>Effet</texte></colonne>
							<colonne id="valeurs_ul"><texte>Valeur(s)</texte></colonne>
						</ligne>
						<ligne>
							<colonne headers="attr_ul"><texte><code>type</code></texte></colonne>
							<colonne headers="effet_ul"><texte>Choix du type de puce</texte></colonne>
							<colonne headers="valeurs_ul">
								<liste type="sanspuce">
									<item><texte><image alt="disc" hauteur="15" largeur="15" src="exemples/disc.gif"/>disc (défaut)</texte></item>
									<item><texte><image alt="circle" hauteur="15" largeur="15" src="exemples/circle.gif"/>circle</texte></item>
									<item><texte><image alt="square" hauteur="15" largeur="15" src="exemples/square.gif"/>square</texte></item>
								</liste>
							</colonne>
						</ligne>
						<legende>Attribut <valeur>obsolète</valeur> de la balise ul.</legende>
					</tableau>
					<texte> Exemple d'utilisation&#160;: </texte>
					<exemple type="HTML">
						<element nom="ul" indent="oui">
							<element nom="li" niveau="1">Premier élément</element>
							<element nom="li" niveau="1">Deuxième élément</element>
							<element nom="li" niveau="1">Troisième élément</element>
						</element>
					</exemple>
				</paragraphe>
				<paragraphe ancre="numeros" titre="Listes numérotées">
					<texte>Ce type de listes est ordonnée. Elle s'introduit en utilisant la balise <code><![CDATA[<ol>]]></code>, qui signifie <autrelangue> <valeur>O</valeur>rdered <valeur>L</valeur>ist</autrelangue>. Les éléments de la liste sont également déclarés par la balise <code>&lt;li&gt;</code>. La "numérotation" peut se faire de cinq manières différentes, cela étant spécifié par la valeur de l'attribut <code>type</code>. Elle peut débuter à n'importe quelle position (par exemple à 2...), grâce à la valeur de l'attribut obsolète <code>start</code>.</texte>
					<tableau>
						<ligne type="header">
							<colonne id="attr_ol"><texte>Attribut</texte></colonne>
							<colonne id="effet_ol"><texte>Effet</texte></colonne>
							<colonne id="valeurs_ol"><texte>Valeur(s)</texte></colonne>
						</ligne>
						<ligne>
							<colonne headers="attr_ol"><texte><code>type</code></texte></colonne>
							<colonne headers="effet_ol"><texte>choix du type de numérotation</texte></colonne>
							<colonne headers="valeurs_ol">
								<liste type="sanspuce">
									<item><texte>1 (par défaut)</texte></item>
									<item><texte>a</texte></item>
									<item><texte>A</texte></item>
									<item><texte>i</texte></item>
									<item><texte>I</texte></item>
								</liste>
							</colonne>
						</ligne>
						<ligne>
							<colonne><texte><code>start</code></texte></colonne>
							<colonne><texte>numéro de début de liste</texte></colonne>
							<colonne><texte>selon le type, un numéro ou une lettre</texte></colonne>
						</ligne>
						<legende>Attributs <valeur>obsolètes</valeur> de la balise <code>&lt;ol&gt;</code></legende>
					</tableau>
					<texte>La balise <code><![CDATA[<li>]]></code> possède alors un autre attribut,<code>value</code>, analogue au rôle de <code>start</code>, qui permet de spécifier le rang de l'item, et donc d'imposer des sauts dans la numérotation.</texte>
				</paragraphe>
				<paragraphe ancre="definition" titre="Liste de définitions">
					<texte>Ce type de liste, peu usité, est une... liste de définitions&#160;! Elle est déclarée par la balise <code><![CDATA[<dl>]]></code>. Par exemple&#160;:</texte>
					<exemple type="HTML">
						<element nom="dl" indent="oui">
							<element nom="dt" niveau="1">basilic</element>
							<element nom="dd" niveau="1">Annuelle. Peut dépasser un mètre de hauteur. Le parfum de ses petites fleurs blanches est divin.</element>
							<element nom="dt" niveau="1">origan</element>
							<element nom="dd" niveau="1">Vivace. Propage ses stolons sous terre. Il est difficile de s'en débarrasser une fois bien établi.</element>
							<element nom="dt" niveau="1">coriandre</element>
							<element nom="dd" niveau="1">Annuelle. Préfère une situation ombragée. Son huile est utilisée en parfumerie.</element>
						</element>
					</exemple>
					<texte> Il n'y a pas d'attribut spécial pour cette balise. </texte>
				</paragraphe>
			</section>
			<section ancre="imbriquees" titre="Listes imbriquées">
				<paragraphe>
					<texte>Les puces et la numérotation varient selon le rang de la liste. Par exemple, pour des listes non ordonnées, on obtient&#160;:</texte>
					<liste>
						<item>
							<texte>Premier niveau</texte>
							<liste>
								<item>
									<texte>Deuxième niveau</texte>
									<liste>
										<item>
											<texte>Troisième niveau</texte>
											<liste>
												<item><texte>Quatrième niveau</texte></item>
											</liste>
										</item>
									</liste>
								</item>
							</liste>
						</item>
					</liste>
				</paragraphe>
			</section>
			<exercice titre="Listes et liens" ancre="exolistes">
				<enonce href="exercices/td2.html"/>
				<correction href="exercices/td2cor.html"/>
			</exercice>
		</partie>
	</corpus>
</chapitre>
