=== RachelBdeS/RachelBdeS.github.io/_Sommaire/Cours/ressources/chapitre22.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- L'historique de cette DTD présentant ses diverses versions est dans le fichier historiqueChapitre.dtd.txt-->

<!-- ================ Declarations d'entites ============================= -->
<!--<!ENTITY % HTMLspecial PUBLIC "-//W3C//ENTITIES Special for XHTML//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml-special.ent">-->
<!ENTITY % HTMLspecial SYSTEM "xhtml-special.ent">
%HTMLspecial;
<!ENTITY % URI "CDATA">
<!ENTITY % enligne "#PCDATA | definition | valeur | index | autrelangue | code | reference | acronyme | abreviation| image | logiciel | puissance">
<!ENTITY % bloc "image | texte | liste | définitions | exemple | exemplejavascript | exemple_css | tableau | imagereactive">
<!-- =================== Declarations d'elements ============================== -->
<!ELEMENT chapitre (cours, entete, corpus)>
	<!ATTLIST chapitre  typecourssiteweb (xml|html|dhtml) #REQUIRED>
<!ELEMENT cours (#PCDATA)>
<!-- Nom du fichier XML sans l'extension -->
	<!ATTLIST cours nomfichier CDATA #REQUIRED >
<!--    Declarations des elements de l'entete     -->
	<!ELEMENT entete (titre, auteur, resume, motsclefs)>
		<!ELEMENT titre (#PCDATA)>
		<!ELEMENT auteur (#PCDATA)>
			<!ATTLIST auteur
				email CDATA #IMPLIED
			>
			
	<!ELEMENT resume (#PCDATA)>
	<!ELEMENT motsclefs (#PCDATA)>
	
<!--  Declarations des elements du corps du cours   -->
<!ELEMENT corpus (partie*, bibliographie?)>
<!ELEMENT partie (section | exercice | paragraphe)*>
<!ELEMENT section (paragraphe | liste | exercice)*>
<!ELEMENT paragraphe (%bloc;)*>
<!ATTLIST paragraphe
	titre CDATA #IMPLIED
	auteur CDATA ""
	date CDATA ""
	href %URI; ""
	ancre ID #IMPLIED
>
<!ELEMENT liste (item)*>

<!ELEMENT item (%bloc;)*>
<!ATTLIST liste
	type (envrac | ordonnee | sanspuce) "envrac"
>

<!ELEMENT définitions (terme,def+)+>

<!ELEMENT terme (%enligne;)* >
<!ELEMENT def (%enligne;)* >

<!ELEMENT tableau (groupecolonne*,ligne*, legende?)>
<!ATTLIST tableau
	bordure CDATA "1"
>
<!ELEMENT groupecolonne EMPTY>
	<!ATTLIST groupecolonne
		nombre CDATA "1"
		largeur CDATA #IMPLIED
	>
<!ELEMENT ligne (colonne*)>
<!ELEMENT colonne (%bloc;)*>
<!ATTLIST colonne
	type (header | normal) "normal"
	id ID #IMPLIED
	abbr CDATA #IMPLIED
	headers IDREFS #IMPLIED
>
<!ATTLIST ligne
	type (header | normal) "normal"
>
<!ELEMENT legende (%enligne;)*>

<!ELEMENT image (legende?)>
<!ATTLIST image
	src %URI; #REQUIRED
	hauteur CDATA ""
	largeur CDATA ""
	alt CDATA #REQUIRED
	classe (normal | illustration) "normal"
>
<!ELEMENT imagereactive (zone+, legende?)>
<!ATTLIST imagereactive
	src %URI; #REQUIRED
	hauteur CDATA ""
	largeur CDATA ""
	alt CDATA #REQUIRED
	nom CDATA #REQUIRED
>
<!ELEMENT zone EMPTY>
<!ATTLIST zone
	forme (rect | circle | poly | default) "rect"
	coords CDATA #IMPLIED
	href %URI; #IMPLIED
	alt CDATA #REQUIRED
>
<!ELEMENT texte (%enligne;)*>
<!ATTLIST section
	titre CDATA #REQUIRED
	auteur CDATA ""
	date CDATA ""
	href %URI; ""
	ancre ID #REQUIRED
>
<!ELEMENT exercice (remarque?,enonce?, correction*)>
<!ELEMENT remarque (#PCDATA)>
<!ELEMENT enonce EMPTY>
<!ATTLIST enonce
	href %URI; ""
>
<!ELEMENT correction EMPTY>
<!ATTLIST correction
	href %URI; #REQUIRED
	description CDATA #IMPLIED
>
<!ATTLIST exercice
	titre CDATA #REQUIRED
	auteur CDATA ""
	date CDATA ""
	ancre ID #REQUIRED
>
<!ATTLIST partie
	titre CDATA #REQUIRED
	auteur CDATA ""
	date CDATA ""
	href %URI; ""
	ancre ID #REQUIRED
>

<!-- Definitions d'elements en-ligne -->
<!ELEMENT acronyme (#PCDATA)>
	<!ATTLIST acronyme
		titre CDATA #REQUIRED
		lang CDATA #IMPLIED
	>
<!ELEMENT abreviation (#PCDATA|code)*>
	<!ATTLIST abreviation
		titre CDATA #REQUIRED
		lang CDATA #IMPLIED
	>
<!ELEMENT index (#PCDATA)>
<!ATTLIST index
	type (visible | hidden) "hidden"
	id ID #REQUIRED
>
<!ELEMENT definition (#PCDATA)>
<!ATTLIST definition
	clef CDATA #REQUIRED
	lang CDATA #IMPLIED
>

<!ELEMENT autrelangue (%enligne;)*>
<!ATTLIST autrelangue
	type CDATA "en"
>
<!ELEMENT valeur ANY>
<!ATTLIST valeur
 	lang CDATA #IMPLIED
 >
<!ELEMENT code (#PCDATA)>
<!ATTLIST code
	type (langage | code | typefichier) "code"
	option (yes | no) "no"
>
<!ELEMENT logiciel (#PCDATA)* >
<!ATTLIST logiciel
 	lang CDATA #IMPLIED
 >

<!ELEMENT exemple (prologue | instruction_traitement | element | commentaire | typedocument | cdat | declaration_element | declaration_entite | typedocument_interne)*>
<!ATTLIST exemple
	type (XML | HTML | illustration) #REQUIRED
	ancre ID #IMPLIED
>

<!ELEMENT prologue EMPTY>
<!ATTLIST prologue
	encodage CDATA "ISO-8859-1"
	version CDATA "1.0"
	standalone (yes | no) #IMPLIED 
>

<!ELEMENT instruction_traitement EMPTY >
<!ATTLIST instruction_traitement
	nom CDATA #REQUIRED
	type CDATA #REQUIRED
	href %URI; #REQUIRED
>

<!ELEMENT element (#PCDATA | attribut |commentaire | element | cdat | contenu)* >
<!ATTLIST element
 	nom CDATA #REQUIRED
 	enligne (oui | non) "non"
 	indent (oui | non) "non"
	niveau CDATA "0"
	vide (oui | non) "non"
 >
 
 <!ELEMENT contenu (#PCDATA)>
 <!-- Cet élément est réservé aux éléments non en ligne pour lequel un contenu doit être inséré à la ligne. Par exemple :<style>
     (...)
 </style>
 -->
 <!ATTLIST contenu niveau CDATA "0" >
 
 <!ELEMENT attribut (#PCDATA)>
 <!ATTLIST attribut
 	nom CDATA #REQUIRED
 	pseudo (non | oui) "non"
 >
 
 <!ELEMENT commentaire (#PCDATA)>
 	<!ATTLIST commentaire niveau CDATA "0">
  <!ELEMENT cdat (#PCDATA)>
  
  <!ELEMENT typedocument EMPTY>
  <!ATTLIST typedocument
  	nomracine CDATA #REQUIRED
  	type (SYSTEM|PUBLIC|...) #REQUIRED
  	identifiant CDATA #IMPLIED
  	href %URI; #REQUIRED
 >
 
 <!ELEMENT typedocument_interne (declaration_element | declaration_entite)*>
   <!ATTLIST typedocument_interne
  	nomracine CDATA #REQUIRED
  >
 
 <!ELEMENT declaration_element (declaration_attribut*)>
 <!ATTLIST declaration_element
 	nom CDATA #REQUIRED
 	type CDATA #REQUIRED
 >
 
  <!ELEMENT declaration_attribut EMPTY>
 <!ATTLIST declaration_attribut
 	nomattr CDATA #REQUIRED
 	valeur CDATA #REQUIRED
 	type (IMPLIED | REQUIRED | FIXED | chaine) #REQUIRED
 	defaut CDATA #IMPLIED
 >
 
 <!ELEMENT declaration_entite EMPTY>
  <!ATTLIST declaration_entite
 	nom CDATA #REQUIRED
 	valeur CDATA #REQUIRED
 	type (paramétrique | caractères) "caractères"
 	syspub (system | public | autre) "autre"
 	identifiant CDATA #IMPLIED
 >

<!ELEMENT exemple_css (csselt|commentaireCSS)* >
<!ELEMENT commentaireCSS (#PCDATA) >
<!ELEMENT csselt (selecteur, prop+)>
<!ELEMENT selecteur (#PCDATA)>
<!ELEMENT prop EMPTY>
<!ATTLIST prop
	nom CDATA #REQUIRED
	valeur CDATA #REQUIRED
>
	
<!ELEMENT exemplejavascript (fonction | instruction | variable | propriete | declaration | autres | finligne | sautligne | bloc | commentaire_js)*>
<!ELEMENT bloc (fonction | instruction | variable | propriete | declaration | autres | finligne | sautligne | bloc | commentaire_js)* >
	<!ATTLIST bloc
		niveau CDATA "0"
		avec_retour (vrai|faux) "vrai">
<!ELEMENT fonction (variable | autres | propriete | fonction)*>
	<!ATTLIST fonction
		name CDATA #REQUIRED
		niveau CDATA "0">
<!ELEMENT instruction EMPTY>
	<!ATTLIST instruction
		name CDATA #REQUIRED
		niveau CDATA "0">
<!ELEMENT variable EMPTY>
	<!ATTLIST variable
		name CDATA #REQUIRED
		niveau CDATA "0">
<!ELEMENT propriete EMPTY>
	<!ATTLIST propriete
		name CDATA #REQUIRED
		niveau CDATA "0">
<!ELEMENT declaration EMPTY>
	<!ATTLIST declaration
		nomvariable CDATA #REQUIRED
		valeur CDATA #REQUIRED
		new (oui|non) "oui"
		niveau CDATA "0">
<!ELEMENT autres (#PCDATA)>
	<!ATTLIST autres niveau CDATA "0" >
<!ELEMENT finligne EMPTY>
	<!ATTLIST finligne caractère CDATA ";" >
<!ELEMENT sautligne EMPTY>
<!ELEMENT commentaire_js (#PCDATA|sautligne)*>
	<!ATTLIST commentaire_js niveau CDATA "0" >

<!ELEMENT reference ANY>
<!ATTLIST reference
	href %URI; #REQUIRED
	lang CDATA #IMPLIED
>

<!ELEMENT puissance (#PCDATA) >

<!ELEMENT bibliographie (author, titre, editeur, lien, commentaire)?>
<!ELEMENT author (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT editeur (#PCDATA)>
<!ELEMENT lien (#PCDATA)>
<!ATTLIST bibliographie
	auteur CDATA ""
	date CDATA ""
	href %URI; ""
>

=== RachelBdeS/RachelBdeS.github.io/_Sommaire/Cours/html/video.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE chapitre SYSTEM "../ressources/chapitre22.dtd">

<chapitre typecourssiteweb="html">
	<cours nomfichier="video">Cours de HTML</cours>
	<entete>
		<titre>Contrôle du son et de la vidéo</titre>
		<auteur email="Gilles.Chagnon@upmc.fr">G. Chagnon</auteur>
		<resume>Comment insérer du contenu multimédia dans une page Web&#160;?</resume>
		<motsclefs>html, object, embed, param</motsclefs>
	</entete>
	<corpus>
		<partie ancre="plugin" titre="Les modules externes">
			<section ancre="definition" titre="Qu'appelle-t-on ''module externe'' ou ''plug-in''?">
				<paragraphe>
					<texte>Bien que le son et la vidéo soient le propre du multimédia, les navigateurs ne sont pas capables de les exécuter seuls&#160;: ils disposent d'une architecture ouverte qui leur permet de faire appel à des programmes supplémentaires externes. Ce sont les <autrelangue>plug-in</autrelangue>.</texte>
					<texte>Par exemple, cliquer sur ce point d'interrogation <reference href="sons/ringin.wav"><image alt="Point d'interrogation" hauteur="18" largeur="18" src="images/b2_help.gif"/></reference>. Vous ferez appel implicitement au <autrelangue>plug-in</autrelangue> par défaut de lecture d'un son du type <code type="typefichier">wav</code>. Ce <autrelangue>plug-in</autrelangue> par défaut dépend des configurations de la machine de l'utilisateur&#160;: selon les installations, ce pourra être <logiciel>MédiaPlayer</logiciel>, le magnétophone de Windows...</texte>
					<texte>Ces programmes sont souvent installés avec le navigateur ou bien disponibles, généralement gratuitement, sur Internet.</texte>
				</paragraphe>
			</section>
			<section ancre="nn" titre="Visualiser ses ''plug-ins'' sous NN">
				<paragraphe>
					<texte>Il est possible de visualiser sous <logiciel>Netscape Navigator</logiciel>, l'ensemble des <autrelangue>plug-in</autrelangue> disponibles pour ce navigateur. Il suffit d'effectuer le cheminement suivant&#160;: <code>Help&gt;A propos des modules externes</code>. Cet enchaînement lance un <code type="langage">JavaScript</code> capable d'analyser ce qui est disponible. Lancer cette commande et examiner le résultat.</texte>
				</paragraphe>
			</section>
			<section ancre="nnie" titre="Des dispositions différentes sous NN et IE">
				<paragraphe>
					<texte>L'apparition des <autrelangue>plug-ins</autrelangue> revient à NetScape avec la version 2 de <logiciel>Navigator</logiciel>&#160;: grâce aux <autrelangue>plug-ins</autrelangue>, il est devenu alors possible de lire n'importe quel type de fichier à même la fenêtre du navigateur. La réaction de MicroSoft fut alors de reprendre le concept de <autrelangue>plug-in</autrelangue> et de l'approfondir&#160;: ce fut la technologie <code type="langage">ActiveX</code> (<code type="langage">ActiveX</code> est un langage de script utilisant les technologies Visual Basic et OLE). Les détails techniques sur cette différence d'approche et de mise en oeuvre sortent du cadre de ce cours&#160;; nous retiendrons simplement que <logiciel>Netscape Navigator</logiciel> et <logiciel>Internet Explorer</logiciel> ne partagent pas la même approche des modules externes. L'effet principal est de nous compliquer (encore une fois&#160;!) la tâche.</texte>
				</paragraphe>
			</section>
			<section ancre="activex" titre="Visualiser les objets ActiveX sous IE">
				<paragraphe>
					<texte>Il est possible de visualiser sous <logiciel>Internet Explorer,</logiciel> l'ensemble des objets Active disponibles pour ce navigateur. Il suffit d'effectuer le cheminement suivant&#160;: <code>Outils&gt;Option Internet&gt;Paramètres (sous l'onglet Général)&gt; Afficher les Objets</code>.</texte>
					<texte>On pourra visualiser les propriétés de ces objets par un clic droit de la souris. On notera l'identifiant de classe (classid) utile pour l'appel de l'objet ActiveX dans la page HTML.</texte>
				</paragraphe>
			</section>
		</partie>
		<partie titre="Balises d'insertion de contenu multimédia" ancre="balises">
			<section ancre="embed" titre="La balise &lt;embed&gt;">
				<paragraphe>
					<texte>Cette balise, initialement introduite par Netscape, ne fait même plus partie de la recommandation <code type="langage">HTML</code> Transitionnel du W3C. Elle permettait d'insérer dans la page <code type='typefichier'>HTML</code> l'exécution du <autrelangue>plug-in</autrelangue> correspondant au type du fichier.</texte>
					<texte>Le W3C recommande l'utilisation de la balise <code><![CDATA[<object>]]></code>.</texte>
				</paragraphe>
			</section>
			<section ancre="object" titre="La balise &lt;object&gt;">
				<paragraphe ancre="syntaxeobject" titre="Syntaxe">
					<texte>La balise <code><![CDATA[<object>]]></code> est utilisée pour inclure images, séquences video, applets Java et interfaces VRML. Cette balise est prévue pour remplacer les balises à usage plus limité <code><![CDATA[<img>]]></code> et <code><![CDATA[<applet>]]></code>, ainsi que les éléments propriétaires <code><![CDATA[<embed>]]></code> et <code><![CDATA[<bgsound>]]></code>, en dépit de problèmes relatifs à son support par les navigateurs. Dans la mesure du possible, on continuera donc à utiliser les balises <code><![CDATA[<img>]]></code> et <code><![CDATA[<applet>]]></code>.</texte>
					<texte>Cette balise accepte plusieurx attributs principaux&#160;:</texte>
					<liste>
						<item><texte><code>data</code>&#160;: spécifie l'URI (adresse) de l'objet inséré.</texte></item>
						<item><texte>Les attributs <code>width</code> et <code>height</code> définissent les dimensions de l'objet. La valeur peut être exprimée en nombre de pixels ou en pourcentages de la taille de l'élément contenant l'objet. <valeur>Attention&#160;:</valeur> la plupart des navigateurs requièrent la présence de ces attributs.</texte></item>
						<item><texte><code>classid&gt;</code> peut être utilisé pour définir une implémentation permettant la gestion de l'objet. Cela est le cas pour les applets Java et Python, les contrôles ActiveX, ainsi que le montre l'exemple suivant...</texte></item>
					</liste>
					<exemple type="HTML">
						<element nom="object" indent="oui">
							<attribut nom="classid">yahtzee.py</attribut>
							<attribut nom="codetype">application/x-python</attribut>
							<attribut nom="standby">Prêt pour un petit Yahtzee?</attribut>
							<attribut nom="title">Mon Yahtzee</attribut>
							<element nom="object" niveau="1" indent="oui">
								<attribut nom="classid">java:Yahtzee.class</attribut>
								<attribut nom="codetype">application/java</attribut>
								<attribut nom="width">400</attribut>
								<attribut nom="height">250</attribut>
								<attribut nom="standby">Prêt pour un petit Yahtzee?</attribut>
								<attribut nom="title">Mon Yahtzee</attribut>
								<element nom="object" niveau="2">
									<attribut nom="data">yahtzee.gif</attribut>
									<attribut nom="type">image/gif</attribut>
									<attribut nom="title">Une animation Yahtzee</attribut>
									<attribut nom="width">200</attribut>
									<attribut nom="height">100</attribut>
									Yahtzee est mon <element nom="em" enligne="oui">jeu favori</element>.
								</element>
							</element>
						</element>
					</exemple>
					<texte>Cet exemple montre aussi une solution afin de permettre aux navigateurs qui ne peuvent supporter le type d'objet, d'afficher une alternative. Dans cet exemple, le jeu écrit en <code type="langage">Python</code> est utilisé si le navigateur le supporte. Au cas où cela ne serait pas possible, une version Java est disponible. Une troisième possibilité est offerte avec l'affichage d'une image, et enfin une dernière alternative est disponible avec du texte brut. Cette possibilité préserve la compatibilité avec les plus anciens navigateurs, qui ignoreront les éléments <code><![CDATA[<object>]]></code>, et se contenteront d'afficher le texte.</texte>
					<texte>L'exemple précédent utilise également les attributs <code>type</code> et <code>codetype</code> pour aider les navigateurs à déterminer la nature des fichiers en jeu&#160;: cela leur évite ainsi de tenter de charger un type de fichier qu'ils ne savent pas gérer. L'attribut <code>type</code> indique le type de média de la ressource référencée par l'attribut <code>data</code>, tandis que l'attribut <code>codetype</code> indique le type de média de la ressource référencée par l'attribut <code>classid</code>.</texte>
					<texte>L'attribut <code>standby</code> est aussi utilisé dans l'exemple précédent. Il fournit un court texte affiché dans la fenêtre pendant le chargement de l'objet.</texte>
				</paragraphe>
				<paragraphe ancre="param" titre="Elément &lt;param&gt;">
					<texte>L'élément <code><![CDATA[<object>]]></code> peut contenir des éléments <code><![CDATA[<param>]]></code>, <valeur>avant</valeur> tout autre élément-enfant, permettant de spécifier un certain nombre de propriétés qui sont transmises aux objets multimédia chargés. Par exemple,</texte>
					<exemple type="HTML">
						<element nom="object" indent="oui">
							<attribut nom="classid">java:Clock.class</attribut>
							<attribut nom="codetype">application/java</attribut>
							<attribut nom="width">100</attribut>
							<attribut nom="height">100</attribut>
							<attribut nom="title">Une horloge en temps réel!</attribut>
							<attribut nom="standby">Quelle heure est-il?</attribut>
							<element nom="param" niveau="1"><attribut nom="name">type</attribut><attribut nom="value">analog</attribut></element>
							<element nom="param" niveau="1"><attribut nom="name">bgcolor</attribut><attribut nom="value">white</attribut></element>
							<element nom="param" niveau="1"><attribut nom="name">fgcolor</attribut><attribut nom="value">navy</attribut></element>
						</element>
					</exemple>
				</paragraphe>
			</section>
		</partie>
	</corpus>
</chapitre>

=== RachelBdeS/RachelBdeS.github.io/_Sommaire/Cours/html/modeles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE chapitre SYSTEM "../ressources/chapitre22.dtd">

<chapitre typecourssiteweb="html">
	<cours nomfichier="modeles">Cours de HTML</cours>
	<entete>
		<titre>Modèles de documents et de codes</titre>
		<auteur email="Gilles.Chagnon@upmc.fr">G. Chagnon</auteur>
		<resume>Ce chapitre propose des modèles de documents et de code HTML.</resume>
		<motsclefs>html, base, modele, modeles</motsclefs>
	</entete>
	<corpus>
		<partie titre="Modèles de documents" ancre="documents">
			<section titre="Introduction" ancre="docintro">
				<paragraphe>
					<texte>Cette partie présente des modèles de documents-types. Il va de soi que ces modèles doivent être complétés. Ils donnent les bases pour fournir des documents pouvant être traités par le <reference href="http://validator.w3.org/file-upload.html">validateur du W3C</reference>.</texte>
				</paragraphe>
			</section>
			<section titre="Modèle de document HTML strict" ancre="docstrict">
				<paragraphe>
					<exemple type="HTML">
						<typedocument nomracine="HTML" type="PUBLIC" href="http://www.w3.org/TR/html4/strict.dtd" identifiant="-//W3C//DTD HTML 4.01//EN"/>
						<commentaire>Déclaration de type de document.</commentaire>
						<element nom="html" indent="oui">
							<attribut nom="lang">fr</attribut>
							<element nom="head" niveau="1" indent="oui">
								<commentaire niveau="2">Déclaration du codage de caractères</commentaire>
								<element nom="meta" niveau="2" vide="oui"><attribut nom="http-equiv">Content-Type</attribut><attribut nom="content">text/html; charset=ISO-8859-1</attribut></element>
								<element nom="title" niveau="2">(...)</element>
							</element>
							<element nom="body" niveau="1">(...)</element>
						</element>
					</exemple>
				</paragraphe>
			</section>
			
			<section titre="Modèle de document HTML transitionnel" ancre="doctransitional">
				<paragraphe>
					<exemple type="HTML">
						<typedocument nomracine="HTML" type="PUBLIC" href="http://www.w3.org/TR/html4/loose.dtd" identifiant="-//W3C//DTD HTML 4.01 Transitional//EN"/>
						<commentaire>Déclaration de type de document.</commentaire>
						<element nom="html" indent="oui">
							<attribut nom="lang">fr</attribut>
							<element nom="head" niveau="1" indent="oui">
								<commentaire niveau="2">Déclaration du codage de caractères</commentaire>
								<element nom="meta" niveau="2" vide="oui"><attribut nom="http-equiv">Content-Type</attribut><attribut nom="content">text/html; charset=ISO-8859-1</attribut></element>
								<element nom="title" niveau="2">(...)</element>
							</element>
							<element nom="body" niveau="1">(...)</element>
						</element>
					</exemple>
				</paragraphe>
			</section>
			
			
			<section titre="Modèle de document HTML à cadres" ancre="docframes">
				<paragraphe>
					<exemple type="HTML">
						<typedocument nomracine="HTML" type="PUBLIC" href="http://www.w3.org/TR/html4/frameset.dtd" identifiant="-//W3C//DTD HTML 4.01 Frameset//EN"/>
						<commentaire>Déclaration de type de document.</commentaire>
						<element nom="html" indent="oui">
							<attribut nom="lang">fr</attribut>
							<element nom="head" niveau="1" indent="oui">
								<commentaire niveau="2">Déclaration du codage de caractères</commentaire>
								<element nom="meta" niveau="2" vide="oui"><attribut nom="http-equiv">Content-Type</attribut><attribut nom="content">text/html; charset=ISO-8859-1</attribut></element>
								<element nom="title" niveau="2">(...)</element>
							</element>
							<element nom="body" niveau="1">(...)</element>
						</element>
					</exemple>
				</paragraphe>
			</section>
		</partie>
		
		<partie titre="Modèles de codes" ancre="codes">
			<section titre="Mise en forme de texte" ancre="codestexte">
				<paragraphe ancre="parettitre" titre="Paragraphes et titres">
					<texte>Voici par exemple un paragraphe précédé d'un titre&#160;; ces éléments sont des enfants directs de la balise <code><![CDATA[<body>]]></code>.</texte>
					<exemple type="HTML">
						<element nom="h3">Titre de niveau 3</element>
						<element nom="p">Petit paragraphe, avec un<element nom="br" vide="oui"></element>retour à la ligne.</element>
					</exemple>
				</paragraphe>
				<paragraphe titre="Balises div et span" ancre="divspan">
					<texte>La balise <code><![CDATA[<div>]]></code> est un enfant direct de <code><![CDATA[<body>]]></code>, la balise <code><![CDATA[<span>]]></code> est à l'intérieur d'un texte&#160;:</texte>
					<exemple type="HTML">
						<element nom="body" indent="oui">
							<element nom="div" niveau="1" indent="oui">
								<attribut nom="id">premierdiv</attribut>
								<element nom="p" niveau="2">Un paragraphe avec un <element nom="span" enligne="oui">élément span</element>.</element>
							</element>
							<element nom="div" niveau="1" indent="oui">
								<attribut nom="id">seconddiv</attribut>
								<element nom="p" niveau="2">Un deuxième paragraphe.</element>
							</element>
						</element>
					</exemple>
				</paragraphe>
				<paragraphe titre="La balise &lt;font&gt;" ancre="font">
					<texte>Cette balise est obsolète.</texte>
					<exemple type="HTML">
						<element nom="font"><attribut nom="face">Verdana, Arial, Helvetica, sans-serif</attribut><attribut nom="size">5</attribut><attribut nom="color">red</attribut>mon exemple.</element>
					</exemple>
				</paragraphe>
			</section>
			<section titre="Les liens" ancre="liens">
				<paragraphe>
					<texte>Les liens peuvent être de trois types&#160;: interne, relatif, absolu.</texte>
					<exemple type="HTML">
						<commentaire>Lien interne</commentaire>
						<element nom="p">Paragraphe avec un <element nom="a" enligne="oui"><attribut nom="href">#verslancre</attribut>lien interne</element>.</element>
						<commentaire>Lien relatif</commentaire>
						<element nom="p">Paragraphe avec un <element nom="a" enligne="oui"><attribut nom="href">../index.html</attribut>lien relatif</element> vers un fichier du répertoire parent.</element>
						<commentaire>Lien absolu</commentaire>
						<element nom="p">Paragraphe avec un <element nom="a" enligne="oui"><attribut nom="href">http://www.upmc.fr/</attribut>lien absolu</element>.</element>
					</exemple>
				</paragraphe>
			</section>
		</partie>
	</corpus>
</chapitre>
